// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { Artworks as ArtworksData } from "@/types/artworks";

const exhibitions: ArtworksData[] = [
  {
    id: 1,
    title: "Doe",
    slug: "doe",
    artist: 'Isidro "Manong Jon" Santos',
    medium: "etching on aluminum composite panel",
    year: "2022",
    image: { url: "artworks/Doe.jpg", width: 508, height: 650 },
    category: "painting",
    _createdAt: "2023-06-04T08:47:44Z",
    exhibition: "everything-from-scratch",
    width: 18,
    height: 24,
  },
  {
    id: 2,
    title: "Vixen",
    slug: "vixen",
    artist: "Je An Govinda Marquesto",
    medium: "etching on aluminum composite panel",
    year: "2022",
    image: { url: "artworks/Vixen.jpg", width: 510, height: 650 },
    category: "sculpture",
    _createdAt: "2023-06-04T06:47:44Z",
    exhibition: "everything-from-scratch",
    width: 18,
    height: 24,
  },
  {
    id: 3,
    title: "Cosset",
    slug: "cosset",
    artist: "Mayi Peñaflorida",
    medium: "etching on aluminum composite panel",
    year: "2022",
    image: { url: "artworks/Cosset.jpg", width: 507, height: 650 },
    category: "sculpture",
    _createdAt: "2023-06-04T04:47:44Z",
    exhibition: "katapat",
    width: 18,
    height: 24,
  },
  {
    id: 4,
    title: "The Gathering",
    slug: "the-gathering",
    artist: "Je An Govinda Marquesto",
    medium: "etching on aluminum composite panel",
    year: "2022",
    image: { url: "artworks/The-Gathering.jpg", width: 826, height: 650 },
    category: "sculpture",
    _createdAt: "2023-06-04T02:47:44Z",
    exhibition: "katapat",
    width: 24,
    height: 30,
  },
  {
    id: 5,
    title: "Blast Off!",
    slug: "blast-off",
    artist: "Je An Govinda Marquesto",
    medium: "oil on canvas",
    year: "2022",
    image: { url: "artworks/Blast-Off.jpg", width: 532, height: 650 },
    category: "painting",
    _createdAt: "2023-06-04T00:47:44Z",
    exhibition: "inside-the-toy-box",
    width: 24,
    height: 30,
  },
  {
    id: 6,
    title: "Confectionery",
    slug: "confectionery",
    artist: "Mayi Peñaflorida",
    medium: "oil on canvas",
    year: "2022",
    image: { url: "artworks/Confectionery.jpg", width: 529, height: 650 },
    category: "painting",
    _createdAt: "2023-06-03T22:47:44Z",
    exhibition: "inside-the-toy-box",
    width: 24,
    height: 30,
  },
  {
    id: 7,
    title: "Up, We Go!",
    slug: "up-we-Go",
    artist: "Mayi Peñaflorida",
    medium: "oil on canvas",
    year: "2022",
    image: { url: "artworks/Up-We-Go.jpg", width: 537, height: 650 },
    category: "painting",
    _createdAt: "2023-06-03T20:47:44Z",
    exhibition: "visayas-art-fair",
    width: 24,
    height: 30,
  },
  {
    id: 8,
    title: "Love Knots",
    slug: "love-knots",
    artist: "Mayi Peñaflorida",
    medium: "oil on canvas",
    year: "2022",
    image: { url: "artworks/Love-Knots.jpg", width: 523, height: 650 },
    category: "painting",
    _createdAt: "2023-06-03T18:47:44Z",
    exhibition: "visayas-art-fair",
    width: 24,
    height: 30,
  },
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<ArtworksData[]>
) {
  res.status(200).json(exhibitions);
}
